### ISSUE TITLE
WinTiler2 - Cant associate Folder with Tiles

### ISSUE THREAD

**Issue by TheBanishingOfMosquito** [rok-povsic/wintiler#1]
Are you the creator of WinTiler2? 
Cant select folders only executables. 
Can you add an option for copypasting file paths?
![image](https://user-images.githubusercontent.com/65665572/156935109-9940c55c-2628-459b-93cd-1029266cd500.png)
![2](https://user-images.githubusercontent.com/65665572/156935126-83c829a7-624d-417a-a660-6b4999ffc8a9.png)

I am not sure if this is a bug. Cant find it.

**Comment by rok-povsic** [comment]
I'm not author of that project. I wasn't even aware of it. Good luck with the issue.
